const express = require('express')
const CookieParser = require('cookie-parser')
const authRoutes  = require('./routes/auth.routes')
const chatRoutes = require('./routes/chat.routes.js')
const app = express()
app.use(express.json())
app.use(CookieParser())
app.use('/api/auth',authRoutes)
app.use('/api/chat',chatRoutes)
module.exports = app